server {
    listen 0.0.0.0:8081;
    server_name localhost;

    root ./www;
    index index.html;
    autoindex off;

    allowed_methods GET;
    client_max_body_size 1000000;

    error_page 403 ./www/errors/403.html;
    error_page 404 ./www/errors/404.html;
    error_page 405 ./www/errors/405.html;
    error_page 413 ./www/errors/413.html;
    error_page 500 ./www/errors/500.html;
    error_page 501 ./www/errors/501.html;
    error_page 505 ./www/errors/505.html;

    location /special {
        root ./www/special;
        index index.html;
        autoindex off;
        allowed_methods GET;

        error_page 404 ./www/errors/location-404.html;
    }
}
