server {
    listen 0.0.0.0:8081;
    server_name tester_webserv;

    root ./YoupiBanane;
    index youpi.bad_extension;
    autoindex off;

    client_max_body_size 100000000;

    allowed_methods GET POST;

    location / {
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        allowed_methods GET;
    }

    location /post_body {
        allowed_methods POST;
        upload_path ./YoupiBanane;
        client_max_body_size 100;
    }

    location /directory {
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        allowed_methods GET POST;
        cgi .bla /webserv/cgi_test;
    }
}